return {
    -- "coffebar/neovim-project",
    -- opts = {
    --     projects = { -- define project roots
    --         "~/projects/*",
    --         "~/.config/*",
    --     },
    --     session_manager_opts = {
    --         autosave_ignore_dirs = {
    --             vim.fn.expand("~"), -- don't create a session for $HOME/
    --             "/tmp",
    --         },
    --         autosave_ignore_filetypes = {
    --             'NvimTree',
    --             'undotree',
    --             "ccc-ui",
    --             "gitcommit",
    --             "gitrebase",
    --             "qf",
    --             "toggleterm",
    --         },
    --     },
    -- },
    -- init = function()
    --     vim.opt.sessionoptions:append("globals")
    -- end,
    -- dependencies = {
    --     { "nvim-lua/plenary.nvim" },
    --     { "nvim-telescope/telescope.nvim", tag = "0.1.4" },
    --     { "Shatur/neovim-session-manager" },
    -- },
    -- lazy = false,
    -- priority = 100,
}
